title: "Your question in one sentence"
body:
  - type: markdown
    attributes:
      value: |
        First, please check if your question has already been asked.
        If it has, please consider adding a comment to the existing discussion instead of creating a new one.

        Finally, try to describe the best you can what you want to achieve or what is your issue, especially by providing a complete self-contained reproducible example.
        This will help us to understand your question and answer it.

        _Thank you for opening this discussion either to ask for help or to report a possible bug!_
  - type: textarea
    attributes:
      label: Description
      description: Start your question/report!
      placeholder: |
        You can include a minimal reproducible example, a code snippet, or a link to a repository.
        Please make sure to include all the necessary information to reproduce your issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        _Thank you for opening this discussion either to ask for help or to report a possible bug!_
