#!/usr/bin/env bash
#
# Documentation Post-render Script
# Removes the transient files generated by pre-render.sh.
#
# @license MIT License
# @copyright 2026 Mickaël Canouil
# @author Mickaël Canouil
#
# assets/social/og-image.png is left alone. It is ignored by Git like the two
# files below, but pre-render.sh caches it rather than generating it, and a
# render with no network reuses whatever is there.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_DIR="$(dirname "${SCRIPT_DIR}")"

rm -f "${DOCS_DIR}/changelog.qmd" "${DOCS_DIR}/_variables.yml"
printf '[post-render] Removed changelog.qmd and _variables.yml\n'

# Staged by _scripts/gallery.sh from templates/. The originals are committed
# there, so nothing is lost by clearing the copies.
rm -rf \
	"${DOCS_DIR}/templates" \
	"${DOCS_DIR}/assets/slides" \
	"${DOCS_DIR}/assets/pdf" \
	"${DOCS_DIR}/assets/typ" \
	"${DOCS_DIR}/assets/previews"
printf '[post-render] Removed the staged gallery assets and pages\n'
